apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db  # Alinhado com o Service
  template:
    metadata:
      labels:
        app: db  # Alinhado com o Service
    spec:
      containers:
        # Container da API
        - name: api-cardapio
          image: japamanoel/foodorder_cardapio:latest
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secrets      
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:9000"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: $POSTGRES_URL # value: "Host=db-service;Port=5432;Database=foodorderdb;Username=postgres;Password=postgres"
          command:
            - "sh"
            - "-c"
            - |
              echo "Iniciando API..." &&
              dotnet FoodOrder.API.dll
        - name: api-pagamento
          image: diegogl12/food-order-pagamento:latest
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secrets      
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:9000"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: $POSTGRES_URL # value: "Host=db-service;Port=5432;Database=foodorderdb;Username=postgres;Password=postgres"
          command:
            - "sh"
            - "-c"
            - |
              echo "Iniciando API..." &&
              dotnet FoodOrder.API.dll
        - name: api-pedido
          image: vilacaro/pedido:latest
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secrets      
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:9000"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: $POSTGRES_URL # value: "Host=db-service;Port=5432;Database=foodorderdb;Username=postgres;Password=postgres"
          command:
            - "sh"
            - "-c"
            - |
              echo "Iniciando API..." &&
              dotnet FoodOrder.API.dll
        - name: api-usuarios
          image: vilacaro/api:latest
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secrets      
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:9000"
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: $POSTGRES_URL # value: "Host=db-service;Port=5432;Database=foodorderdb;Username=postgres;Password=postgres"
          command:
            - "sh"
            - "-c"
            - |
              echo "Iniciando API..." &&
              dotnet FoodOrder.API.dll